from __future__ import annotations

from typing import Any

from app.domain import Part, PartCategory
from app.features.builds.catalog_accessories import accessory_parts
from app.features.builds.catalog_expansion import apply_ladder_metadata, expanded_parts


def fixture_parts() -> list[Part]:
    """可复现的本地参考目录；真实渠道通过同样的 Part 结构接入。"""

    def part(
        item_id: str,
        category: PartCategory,
        name: str,
        brand: str,
        price: float,
        specs: dict,
        power_w: int = 0,
    ) -> Part:
        return Part(
            id=item_id,
            category=category,
            name=name,
            brand=brand,
            price=price,
            source="Fixture参考价",
            specs=specs,
            power_w=power_w,
        )

    items = [
        part(
            "cpu-7700",
            PartCategory.CPU,
            "Ryzen 7 7700",
            "AMD",
            1599,
            {"socket": "AM5", "tdp": 65, "score": 86},
            65,
        ),
        part(
            "cpu-7800x3d",
            PartCategory.CPU,
            "Ryzen 7 7800X3D",
            "AMD",
            2499,
            {"socket": "AM5", "tdp": 120, "score": 98},
            120,
        ),
        part(
            "cpu-13400f",
            PartCategory.CPU,
            "Core i5-13400F",
            "Intel",
            1099,
            {"socket": "LGA1700", "tdp": 65, "score": 78},
            65,
        ),
        part(
            "cpu-14600kf",
            PartCategory.CPU,
            "Core i5-14600KF",
            "Intel",
            1799,
            {"socket": "LGA1700", "tdp": 125, "score": 91},
            125,
        ),
        part(
            "cpu-12600kf",
            PartCategory.CPU,
            "Core i5-12600KF",
            "Intel",
            999,
            {
                "socket": "LGA1700",
                "tdp": 125,
                "score": 82,
                "cores_threads": "10核16线程",
                "base_clock": "3.7GHz",
                "boost_clock": "4.9GHz",
                "integrated_graphics": "不支持核显",
                "l3_cache": "20MB",
                "process": "Intel 7",
                "architecture": "Alder Lake",
                "memory_types": "DDR4 / DDR5",
                "launch_year": "2021",
            },
            125,
        ),
        part(
            "mb-b650m",
            PartCategory.MOTHERBOARD,
            "B650M WiFi 主板",
            "AMD平台",
            899,
            {
                "socket": "AM5",
                "memory_type": "DDR5",
                "form_factor": "mATX",
                "max_memory_gb": 128,
                "memory_slots": 4,
                "m2_slots": 2,
                "sata_ports": 4,
                "gpu_slot": "PCIe4 x16",
            },
        ),
        part(
            "mb-b650",
            PartCategory.MOTHERBOARD,
            "B650 WiFi 主板",
            "AMD平台",
            1299,
            {
                "socket": "AM5",
                "memory_type": "DDR5",
                "form_factor": "ATX",
                "max_memory_gb": 192,
                "memory_slots": 4,
                "m2_slots": 3,
                "sata_ports": 4,
                "gpu_slot": "PCIe5 x16",
            },
        ),
        part(
            "mb-b760m-ddr4",
            PartCategory.MOTHERBOARD,
            "B760M DDR4 主板",
            "Intel平台",
            699,
            {
                "socket": "LGA1700",
                "memory_type": "DDR4",
                "form_factor": "mATX",
                "max_memory_gb": 128,
                "memory_slots": 4,
                "m2_slots": 2,
                "sata_ports": 4,
                "gpu_slot": "PCIe4 x16",
            },
        ),
        part(
            "mb-z790",
            PartCategory.MOTHERBOARD,
            "Z790 DDR5 主板",
            "Intel平台",
            1599,
            {
                "socket": "LGA1700",
                "memory_type": "DDR5",
                "form_factor": "ATX",
                "max_memory_gb": 192,
                "memory_slots": 4,
                "m2_slots": 3,
                "sata_ports": 6,
                "gpu_slot": "PCIe5 x16",
            },
        ),
        part(
            "mb-itx-b650",
            PartCategory.MOTHERBOARD,
            "B650I WiFi Mini-ITX 主板",
            "AMD平台",
            1599,
            {
                "socket": "AM5",
                "memory_type": "DDR5",
                "form_factor": "Mini-ITX",
                "max_memory_gb": 96,
                "memory_slots": 2,
                "m2_slots": 2,
                "sata_ports": 2,
                "gpu_slot": "PCIe4 x16",
            },
        ),
        part(
            "mb-itx-b760",
            PartCategory.MOTHERBOARD,
            "B760I WiFi Mini-ITX DDR5 主板",
            "Intel平台",
            1299,
            {
                "socket": "LGA1700",
                "memory_type": "DDR5",
                "form_factor": "Mini-ITX",
                "max_memory_gb": 96,
                "memory_slots": 2,
                "m2_slots": 2,
                "sata_ports": 2,
                "gpu_slot": "PCIe4 x16",
            },
        ),
        part(
            "gpu-4060ti",
            PartCategory.GPU,
            "GeForce RTX 4060 Ti 8G",
            "NVIDIA",
            2499,
            {
                "length_mm": 245,
                "score": 78,
                "pcie_slot": "PCIe4 x16",
                "power_connectors": ["1x8pin"],
            },
            160,
        ),
        part(
            "gpu-4070s",
            PartCategory.GPU,
            "GeForce RTX 4070 SUPER 12G",
            "NVIDIA",
            4499,
            {
                "length_mm": 300,
                "score": 94,
                "pcie_slot": "PCIe4 x16",
                "power_connectors": ["12VHPWR"],
            },
            220,
        ),
        part(
            "gpu-rx7600",
            PartCategory.GPU,
            "Radeon RX 7600 8G",
            "AMD",
            2099,
            {
                "length_mm": 240,
                "score": 74,
                "pcie_slot": "PCIe4 x16",
                "power_connectors": ["1x8pin"],
            },
            165,
        ),
        part(
            "gpu-rx7800xt",
            PartCategory.GPU,
            "Radeon RX 7800 XT 16G",
            "AMD",
            3899,
            {
                "length_mm": 315,
                "score": 91,
                "pcie_slot": "PCIe4 x16",
                "power_connectors": ["2x8pin"],
            },
            263,
        ),
        part(
            "ram-ddr4-32",
            PartCategory.MEMORY,
            "DDR4 3200 32GB套装",
            "光威",
            399,
            {"memory_type": "DDR4", "capacity_gb": 32},
        ),
        part(
            "ram-ddr5-32",
            PartCategory.MEMORY,
            "DDR5 6000 32GB套装",
            "金百达",
            699,
            {"memory_type": "DDR5", "capacity_gb": 32},
        ),
        part(
            "ram-ddr5-64",
            PartCategory.MEMORY,
            "DDR5 6000 64GB套装",
            "金百达",
            1199,
            {"memory_type": "DDR5", "capacity_gb": 64},
        ),
        part(
            "ssd-1tb-a",
            PartCategory.STORAGE,
            "1TB PCIe 4.0 固态硬盘",
            "西数",
            499,
            {"capacity_gb": 1024, "interface": "PCIe4", "connector": "M.2"},
        ),
        part(
            "ssd-2tb-a",
            PartCategory.STORAGE,
            "2TB PCIe 4.0 固态硬盘",
            "Lexar",
            899,
            {"capacity_gb": 2048, "interface": "PCIe4", "connector": "M.2"},
        ),
        part(
            "psu-650",
            PartCategory.PSU,
            "650W 金牌全模组电源",
            "海韵",
            699,
            {
                "wattage": 650,
                "rating": "Gold",
                "pcie_8pin_count": 2,
                "atx_3_0": False,
                "twelve_vhpwr": False,
            },
        ),
        part(
            "psu-750",
            PartCategory.PSU,
            "750W 金牌全模组电源",
            "安钛克",
            799,
            {
                "wattage": 750,
                "rating": "Gold",
                "pcie_8pin_count": 3,
                "atx_3_0": False,
                "twelve_vhpwr": False,
            },
        ),
        part(
            "psu-850",
            PartCategory.PSU,
            "850W 金牌全模组电源",
            "海韵",
            999,
            {
                "wattage": 850,
                "rating": "Gold",
                "pcie_8pin_count": 3,
                "atx_3_0": True,
                "twelve_vhpwr": True,
            },
        ),
        part(
            "cooler-air",
            PartCategory.COOLING,
            "双塔风冷散热器",
            "利民",
            199,
            {
                "type": "air",
                "height_mm": 157,
                "capacity_w": 220,
                "supported_sockets": ["AM5", "LGA1700"],
            },
        ),
        part(
            "cooler-air-pro",
            PartCategory.COOLING,
            "高性能双塔风冷散热器",
            "九州风神",
            299,
            {
                "type": "air",
                "height_mm": 162,
                "capacity_w": 280,
                "supported_sockets": ["AM5", "LGA1700"],
            },
        ),
        part(
            "cooler-water-240",
            PartCategory.COOLING,
            "240水冷散热器",
            "酷冷至尊",
            499,
            {
                "type": "water",
                "radiator_mm": 240,
                "capacity_w": 280,
                "supported_sockets": ["AM5", "LGA1700"],
            },
        ),
        part(
            "case-matx",
            PartCategory.CASE,
            "紧凑型 mATX 机箱",
            "先马",
            299,
            {
                "form_factor": "mATX",
                "supported_form_factors": ["mATX", "Mini-ITX"],
                "gpu_length_mm": 330,
                "cooler_height_mm": 165,
                "radiator_mm": 240,
            },
        ),
        part(
            "case-atx",
            PartCategory.CASE,
            "通风型 ATX 机箱",
            "乔思伯",
            499,
            {
                "form_factor": "ATX",
                "supported_form_factors": ["ATX", "mATX", "Mini-ITX"],
                "gpu_length_mm": 360,
                "cooler_height_mm": 170,
                "radiator_mm": 360,
            },
        ),
        part(
            "case-itx",
            PartCategory.CASE,
            "小钢炮 Mini-ITX 机箱",
            "乔思伯",
            399,
            {
                "form_factor": "Mini-ITX",
                "supported_form_factors": ["Mini-ITX"],
                "gpu_length_mm": 305,
                "cooler_height_mm": 155,
                "radiator_mm": 240,
            },
        ),
        Part(
            id="mb-asus-tuf-b760m-plus-d4",
            category=PartCategory.MOTHERBOARD,
            name="TUF GAMING B760M-PLUS D4 重炮手",
            brand="华硕 ASUS",
            price=1159,
            source="ZOL公开详情页参考价",
            url="https://detail.zol.com.cn/1441/1440076/param.shtml",
            specs={
                "socket": "LGA1700",
                "chipset": "Intel B760",
                "form_factor": "mATX",
                "memory_type": "DDR4",
                "max_memory_gb": 128,
                "memory_slots": 4,
                "m2_slots": 2,
                "sata_ports": 4,
                "gpu_slot": "PCIe 4.0 x16",
                "pcie_version": "PCI Express 4.0",
                "dimensions": "24.4×24.4cm",
                "motherboard_power_connector": "一个4针，一个8针，一个24针",
                "audio_codec": "集成 Realtek 7.1 声道音效芯片",
            },
            summary="Intel B760 / LGA1700 / DDR4 的 mATX 主板，参数可由 ZOL 公开详情页复核。",
            cautions=["页面金额属于公开参考报价，购买前仍需核对具体店铺与活动。"],
            data_updated_at="2026-08-31",
        ),
    ]

    items.extend(expanded_parts())
    items.extend(accessory_parts())

    insights: dict[str, dict[str, Any]] = {
        "cpu-7800x3d": {
            "summary": "大容量 3D V-Cache 面向高帧率游戏，AM5 平台具备后续升级空间。",
            "rank": 1,
            "benchmark_score": 780000,
            "percentile": 97.8,
            "advantages": ["游戏帧率表现突出", "AM5 平台升级周期较长"],
            "cautions": ["生产力负载并非同价位最强", "建议搭配可靠散热器"],
            "url": "https://diy.pconline.com.cn/tiantitu/cpu/",
        },
        "cpu-14600kf": {
            "summary": "14 核 20 线程的游戏与生产力均衡处理器，适合中高端独显平台。",
            "rank": 2,
            "benchmark_score": 735000,
            "percentile": 91.4,
            "advantages": ["多线程和高频兼顾", "主板与内存选择丰富"],
            "cautions": ["无核显", "高负载功耗较高"],
            "url": "https://diy.pconline.com.cn/tiantitu/cpu/",
        },
        "cpu-7700": {
            "summary": "8 核 16 线程、65W 设计功耗，适合在能效和升级空间之间取平衡。",
            "rank": 3,
            "benchmark_score": 690000,
            "percentile": 86.2,
            "advantages": ["能效表现友好", "自带基础核显便于排障"],
            "cautions": ["极限游戏性能低于 X3D 型号"],
            "url": "https://diy.pconline.com.cn/tiantitu/cpu/",
        },
        "cpu-12600kf": {
            "summary": "10 核 16 线程，单核频率高，支持 DDR4/DDR5，适合控制平台总价。",
            "rank": 4,
            "benchmark_score": 646985,
            "percentile": 81.16,
            "advantages": ["单核性能强，游戏表现稳定", "兼容 DDR4/DDR5，平台搭配灵活"],
            "cautions": ["无核显，必须搭配独立显卡", "满载功耗较高，需关注散热与主板供电"],
            "source": "规格：太平洋电脑网；价格：Fixture参考价",
            "url": "https://product.pconline.com.cn/cpu/intel/1447887.html",
        },
        "cpu-13400f": {
            "summary": "主流预算级混合架构处理器，适合 1080P 与入门 2K 游戏配置。",
            "rank": 5,
            "benchmark_score": 560000,
            "percentile": 74.8,
            "advantages": ["平台成本可控", "主流游戏够用"],
            "cautions": ["无核显", "高端显卡场景可能限制上限"],
            "url": "https://diy.pconline.com.cn/tiantitu/cpu/",
        },
        "gpu-4070s": {
            "summary": "面向 2K 高刷新率与光追体验，12GB 显存适合多数主流游戏。",
            "rank": 1,
            "benchmark_score": 21000,
            "percentile": 94.0,
            "advantages": ["2K 游戏性能强", "DLSS 与光追生态完整"],
            "cautions": ["12VHPWR 供电需确认电源线材", "12GB 显存不适合所有重度 AI 负载"],
            "url": "https://product.pconline.com.cn/vga/c22604/",
        },
        "gpu-rx7800xt": {
            "summary": "16GB 显存与较强光栅性能，适合重视 2K 画质和显存容量的用户。",
            "rank": 2,
            "benchmark_score": 19500,
            "percentile": 91.0,
            "advantages": ["16GB 显存充足", "光栅性能与价格平衡"],
            "cautions": ["光追与部分创作生态弱于同档 NVIDIA", "整卡功耗较高"],
            "url": "https://product.pconline.com.cn/vga/",
        },
        "gpu-4060ti": {
            "summary": "主流 1080P/轻量 2K 显卡，功耗较低并支持 DLSS 3。",
            "rank": 3,
            "benchmark_score": 13400,
            "percentile": 78.0,
            "advantages": ["能效较好", "支持光追与帧生成"],
            "cautions": ["8GB 显存需控制高分辨率材质", "高画质 2K 上限有限"],
            "url": "https://product.pconline.com.cn/vga/",
        },
        "gpu-rx7600": {
            "summary": "适合 1080P 主流游戏的预算显卡，整机成本容易控制。",
            "rank": 4,
            "benchmark_score": 10800,
            "percentile": 74.0,
            "advantages": ["1080P 性价比较好", "标准 8Pin 供电易搭配"],
            "cautions": ["8GB 显存与 2K 高画质空间有限", "光追性能一般"],
            "url": "https://product.pconline.com.cn/vga/",
        },
    }
    for item in items:
        insight = insights.get(item.id)
        if not insight:
            continue
        item.summary = str(insight["summary"])
        item.rank = int(insight["rank"])
        item.benchmark_score = int(insight["benchmark_score"])
        item.percentile = float(insight["percentile"])
        item.advantages = list(insight["advantages"])
        item.cautions = list(insight["cautions"])
        if "source" in insight:
            item.source = str(insight["source"])
        item.url = str(insight["url"])
        item.data_updated_at = "2026-08-30"
    apply_ladder_metadata(items)
    return items
