from __future__ import annotations

from app.domain import Part, PartCategory


def fixture_parts() -> list[Part]:
    """可复现的本地参考目录；真实渠道通过同样的 Part 结构接入。"""

    def part(
        item_id: str,
        category: PartCategory,
        name: str,
        brand: str,
        price: float,
        specs: dict,
        power_w: int = 0,
    ) -> Part:
        return Part(
            id=item_id,
            category=category,
            name=name,
            brand=brand,
            price=price,
            source="Fixture参考价",
            specs=specs,
            power_w=power_w,
        )

    return [
        part(
            "cpu-7700",
            PartCategory.CPU,
            "Ryzen 7 7700",
            "AMD",
            1599,
            {"socket": "AM5", "tdp": 65, "score": 86},
        ),
        part(
            "cpu-7800x3d",
            PartCategory.CPU,
            "Ryzen 7 7800X3D",
            "AMD",
            2499,
            {"socket": "AM5", "tdp": 120, "score": 98},
            120,
        ),
        part(
            "cpu-13400f",
            PartCategory.CPU,
            "Core i5-13400F",
            "Intel",
            1099,
            {"socket": "LGA1700", "tdp": 65, "score": 78},
        ),
        part(
            "cpu-14600kf",
            PartCategory.CPU,
            "Core i5-14600KF",
            "Intel",
            1799,
            {"socket": "LGA1700", "tdp": 125, "score": 91},
            125,
        ),
        part(
            "mb-b650m",
            PartCategory.MOTHERBOARD,
            "B650M WiFi 主板",
            "AMD平台",
            899,
            {
                "socket": "AM5",
                "memory_type": "DDR5",
                "form_factor": "mATX",
                "max_memory_gb": 128,
                "memory_slots": 4,
                "m2_slots": 2,
                "sata_ports": 4,
                "gpu_slot": "PCIe4 x16",
            },
        ),
        part(
            "mb-b650",
            PartCategory.MOTHERBOARD,
            "B650 WiFi 主板",
            "AMD平台",
            1299,
            {
                "socket": "AM5",
                "memory_type": "DDR5",
                "form_factor": "ATX",
                "max_memory_gb": 192,
                "memory_slots": 4,
                "m2_slots": 3,
                "sata_ports": 4,
                "gpu_slot": "PCIe5 x16",
            },
        ),
        part(
            "mb-b760m-ddr4",
            PartCategory.MOTHERBOARD,
            "B760M DDR4 主板",
            "Intel平台",
            699,
            {
                "socket": "LGA1700",
                "memory_type": "DDR4",
                "form_factor": "mATX",
                "max_memory_gb": 128,
                "memory_slots": 4,
                "m2_slots": 2,
                "sata_ports": 4,
                "gpu_slot": "PCIe4 x16",
            },
        ),
        part(
            "mb-z790",
            PartCategory.MOTHERBOARD,
            "Z790 DDR5 主板",
            "Intel平台",
            1599,
            {
                "socket": "LGA1700",
                "memory_type": "DDR5",
                "form_factor": "ATX",
                "max_memory_gb": 192,
                "memory_slots": 4,
                "m2_slots": 3,
                "sata_ports": 6,
                "gpu_slot": "PCIe5 x16",
            },
        ),
        part(
            "mb-itx-b650",
            PartCategory.MOTHERBOARD,
            "B650I WiFi Mini-ITX 主板",
            "AMD平台",
            1599,
            {
                "socket": "AM5",
                "memory_type": "DDR5",
                "form_factor": "Mini-ITX",
                "max_memory_gb": 96,
                "memory_slots": 2,
                "m2_slots": 2,
                "sata_ports": 2,
                "gpu_slot": "PCIe4 x16",
            },
        ),
        part(
            "mb-itx-b760",
            PartCategory.MOTHERBOARD,
            "B760I WiFi Mini-ITX DDR5 主板",
            "Intel平台",
            1299,
            {
                "socket": "LGA1700",
                "memory_type": "DDR5",
                "form_factor": "Mini-ITX",
                "max_memory_gb": 96,
                "memory_slots": 2,
                "m2_slots": 2,
                "sata_ports": 2,
                "gpu_slot": "PCIe4 x16",
            },
        ),
        part(
            "gpu-4060ti",
            PartCategory.GPU,
            "GeForce RTX 4060 Ti 8G",
            "NVIDIA",
            2499,
            {
                "length_mm": 245,
                "score": 78,
                "pcie_slot": "PCIe4 x16",
                "power_connectors": ["1x8pin"],
            },
            160,
        ),
        part(
            "gpu-4070s",
            PartCategory.GPU,
            "GeForce RTX 4070 SUPER 12G",
            "NVIDIA",
            4499,
            {
                "length_mm": 300,
                "score": 94,
                "pcie_slot": "PCIe4 x16",
                "power_connectors": ["12VHPWR"],
            },
            220,
        ),
        part(
            "gpu-rx7600",
            PartCategory.GPU,
            "Radeon RX 7600 8G",
            "AMD",
            2099,
            {
                "length_mm": 240,
                "score": 74,
                "pcie_slot": "PCIe4 x16",
                "power_connectors": ["1x8pin"],
            },
            165,
        ),
        part(
            "gpu-rx7800xt",
            PartCategory.GPU,
            "Radeon RX 7800 XT 16G",
            "AMD",
            3899,
            {
                "length_mm": 315,
                "score": 91,
                "pcie_slot": "PCIe4 x16",
                "power_connectors": ["2x8pin"],
            },
            263,
        ),
        part(
            "ram-ddr4-32",
            PartCategory.MEMORY,
            "DDR4 3200 32GB套装",
            "光威",
            399,
            {"memory_type": "DDR4", "capacity_gb": 32},
        ),
        part(
            "ram-ddr5-32",
            PartCategory.MEMORY,
            "DDR5 6000 32GB套装",
            "金百达",
            699,
            {"memory_type": "DDR5", "capacity_gb": 32},
        ),
        part(
            "ram-ddr5-64",
            PartCategory.MEMORY,
            "DDR5 6000 64GB套装",
            "金百达",
            1199,
            {"memory_type": "DDR5", "capacity_gb": 64},
        ),
        part(
            "ssd-1tb-a",
            PartCategory.STORAGE,
            "1TB PCIe 4.0 固态硬盘",
            "西数",
            499,
            {"capacity_gb": 1024, "interface": "PCIe4", "connector": "M.2"},
        ),
        part(
            "ssd-2tb-a",
            PartCategory.STORAGE,
            "2TB PCIe 4.0 固态硬盘",
            "Lexar",
            899,
            {"capacity_gb": 2048, "interface": "PCIe4", "connector": "M.2"},
        ),
        part(
            "psu-650",
            PartCategory.PSU,
            "650W 金牌全模组电源",
            "海韵",
            699,
            {
                "wattage": 650,
                "rating": "Gold",
                "pcie_8pin_count": 2,
                "atx_3_0": False,
                "twelve_vhpwr": False,
            },
        ),
        part(
            "psu-750",
            PartCategory.PSU,
            "750W 金牌全模组电源",
            "安钛克",
            799,
            {
                "wattage": 750,
                "rating": "Gold",
                "pcie_8pin_count": 3,
                "atx_3_0": False,
                "twelve_vhpwr": False,
            },
        ),
        part(
            "psu-850",
            PartCategory.PSU,
            "850W 金牌全模组电源",
            "海韵",
            999,
            {
                "wattage": 850,
                "rating": "Gold",
                "pcie_8pin_count": 3,
                "atx_3_0": True,
                "twelve_vhpwr": True,
            },
        ),
        part(
            "cooler-air",
            PartCategory.COOLING,
            "双塔风冷散热器",
            "利民",
            199,
            {
                "type": "air",
                "height_mm": 157,
                "capacity_w": 220,
                "supported_sockets": ["AM5", "LGA1700"],
            },
        ),
        part(
            "cooler-air-pro",
            PartCategory.COOLING,
            "高性能双塔风冷散热器",
            "九州风神",
            299,
            {
                "type": "air",
                "height_mm": 162,
                "capacity_w": 280,
                "supported_sockets": ["AM5", "LGA1700"],
            },
        ),
        part(
            "cooler-water-240",
            PartCategory.COOLING,
            "240水冷散热器",
            "酷冷至尊",
            499,
            {
                "type": "water",
                "radiator_mm": 240,
                "capacity_w": 280,
                "supported_sockets": ["AM5", "LGA1700"],
            },
        ),
        part(
            "case-matx",
            PartCategory.CASE,
            "紧凑型 mATX 机箱",
            "先马",
            299,
            {
                "form_factor": "mATX",
                "supported_form_factors": ["mATX", "Mini-ITX"],
                "gpu_length_mm": 330,
                "cooler_height_mm": 165,
                "radiator_mm": 240,
            },
        ),
        part(
            "case-atx",
            PartCategory.CASE,
            "通风型 ATX 机箱",
            "乔思伯",
            499,
            {
                "form_factor": "ATX",
                "supported_form_factors": ["ATX", "mATX", "Mini-ITX"],
                "gpu_length_mm": 360,
                "cooler_height_mm": 170,
                "radiator_mm": 360,
            },
        ),
        part(
            "case-itx",
            PartCategory.CASE,
            "小钢炮 Mini-ITX 机箱",
            "乔思伯",
            399,
            {
                "form_factor": "Mini-ITX",
                "supported_form_factors": ["Mini-ITX"],
                "gpu_length_mm": 305,
                "cooler_height_mm": 155,
                "radiator_mm": 240,
            },
        ),
    ]
